"""pr001 layered model: bronze staging core ops pii

Revision ID: 0001_pr001_layers
Revises:
Create Date: 2026-08-17 16:06:38.044385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_pr001_layers'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr001_generation',
    sa.Column('ingest_id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ingest_id', name=op.f('pk_pr001_generation')),
    sa.UniqueConstraint('source_sha256', name='uq_pr001_generation_source_sha256'),
    schema='bronze'
    )
    op.create_table('pr001_provider_master',
    sa.Column('_ingest_id', sa.String(length=36), nullable=False),
    sa.Column('_row_ordinal', sa.BigInteger(), nullable=False),
    sa.Column('_ingested_at', sa.DateTime(), nullable=False),
    sa.Column('_source_filename', sa.Text(), nullable=False),
    sa.Column('_source_sha256', sa.String(length=64), nullable=False),
    sa.Column('PROVIDER_CODE', sa.Text(), nullable=True),
    sa.Column('PROVIDER_DESCRIPTION', sa.Text(), nullable=True),
    sa.Column('HBRN', sa.Text(), nullable=True),
    sa.Column('PROVIDER_ALIAS_CODE', sa.Text(), nullable=True),
    sa.Column('PROVIDER_TYPE_CODE', sa.Text(), nullable=True),
    sa.Column('CATEGORY_CODE', sa.Text(), nullable=True),
    sa.Column('PMCARE_PANEL_STATUS', sa.Boolean(), nullable=True),
    sa.Column('ADDRESS1', sa.Text(), nullable=True),
    sa.Column('ADDRESS2', sa.Text(), nullable=True),
    sa.Column('ADDRESS3', sa.Text(), nullable=True),
    sa.Column('CITY', sa.Text(), nullable=True),
    sa.Column('POSTCODE', sa.Text(), nullable=True),
    sa.Column('STATE_CODE', sa.Text(), nullable=True),
    sa.Column('MEDILINE_USER', sa.Boolean(), nullable=True),
    sa.Column('OPEN24HOURS', sa.Boolean(), nullable=True),
    sa.Column('OPEN_PUBLIC_HOLIDAYS', sa.Boolean(), nullable=True),
    sa.Column('GL_ELIGIBILITY_STATUS', sa.Boolean(), nullable=True),
    sa.Column('GL_ELIGIBILITY_APPROVE_BY', sa.Text(), nullable=True),
    sa.Column('GL_ELIGIBILITY_APPROVE_DATE', sa.DateTime(), nullable=True),
    sa.Column('DOCTOR_NAME', sa.Text(), nullable=True),
    sa.Column('WEBSITE', sa.Text(), nullable=True),
    sa.Column('VISUAL', sa.Text(), nullable=True),
    sa.Column('GENERAL_PHONE_NO', sa.Text(), nullable=True),
    sa.Column('GENERAL_FAX_NO', sa.Text(), nullable=True),
    sa.Column('PAYMENT_METHOD_CODE', sa.Text(), nullable=True),
    sa.Column('STATUS_CODE', sa.Text(), nullable=True),
    sa.Column('STATUS_BY', sa.Text(), nullable=True),
    sa.Column('STATUS_DATE', sa.DateTime(), nullable=True),
    sa.Column('APPOINMENT_DATE', sa.DateTime(), nullable=True),
    sa.Column('TERMINATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('SUSPENSION_DATE', sa.DateTime(), nullable=True),
    sa.Column('REMARKS', sa.Text(), nullable=True),
    sa.Column('CREATE_BY', sa.Text(), nullable=True),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True),
    sa.Column('MODIFY_BY', sa.Text(), nullable=True),
    sa.Column('MODIFY_DATE', sa.DateTime(), nullable=True),
    sa.Column('ACC_VENDOR_FLAG', sa.Boolean(), nullable=True),
    sa.Column('ACC_VENDOR_FLAG_DATE', sa.DateTime(), nullable=True),
    sa.Column('SYS_ISACTIVE', sa.Boolean(), nullable=True),
    sa.Column('SYS_ADMIN_REMARKS', sa.Text(), nullable=True),
    sa.Column('SYS_TIME_STAMP', sa.DateTime(), nullable=True),
    sa.Column('ROW_GUID', sa.Text(), nullable=True),
    sa.Column('MIX_ROW_ID', sa.BigInteger(), nullable=True),
    sa.Column('isPMRused', sa.Boolean(), nullable=True),
    sa.Column('LATITUDE', sa.Float(), nullable=True),
    sa.Column('LONGITUDE', sa.Float(), nullable=True),
    sa.Column('GST_REG_NO', sa.Text(), nullable=True),
    sa.Column('GST_COMPANY_NAME', sa.Text(), nullable=True),
    sa.Column('GST_COMPANY_REG_NO', sa.Text(), nullable=True),
    sa.Column('STANDARD_HOUR_FROM', sa.Time(), nullable=True),
    sa.Column('STANDARD_HOUR_TO', sa.Time(), nullable=True),
    sa.Column('PUBLIC_HOUR_FROM', sa.Time(), nullable=True),
    sa.Column('PUBLIC_HOUR_TO', sa.Time(), nullable=True),
    sa.Column('OWNERSHIP_CODE', sa.Text(), nullable=True),
    sa.Column('isAME', sa.Boolean(), nullable=True),
    sa.Column('isLTM', sa.Boolean(), nullable=True),
    sa.Column('IsEfarma', sa.Boolean(), nullable=True),
    sa.Column('NO_DOCTOR_MALE', sa.Boolean(), nullable=True),
    sa.Column('NO_DOCTOR_FEMALE', sa.Boolean(), nullable=True),
    sa.Column('isPERKESO', sa.Boolean(), nullable=True),
    sa.Column('isOH', sa.Boolean(), nullable=True),
    sa.Column('QR_ENCRYPTED_TEXT', sa.Text(), nullable=True),
    sa.Column('QR_FILE_PATH', sa.Text(), nullable=True),
    sa.Column('APPS_PHONE_NO', sa.Text(), nullable=True),
    sa.Column('einv_tin_no', sa.Text(), nullable=True),
    sa.Column('einv_sst_no', sa.Text(), nullable=True),
    sa.Column('einv_email', sa.Text(), nullable=True),
    sa.Column('id_LK180', sa.BigInteger(), nullable=True),
    sa.Column('is_TwoStagesVerify', sa.Boolean(), nullable=True),
    sa.Column('IsAME_MPM', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_ingest_id', '_row_ordinal', name=op.f('pk_pr001_provider_master')),
    schema='bronze',
    comment='PMCare incumbent provider master, verbatim. Append-only generations keyed by _ingest_id; idempotent on _source_sha256. Contains personal data and the quarantined QR_* columns — never selected wholesale outside the loader.'
    )
    op.create_index('ix_bronze_pr001_provider_code', 'pr001_provider_master', ['PROVIDER_CODE'], unique=False, schema='bronze')
    op.create_index('ix_bronze_pr001_sha256', 'pr001_provider_master', ['_source_sha256'], unique=False, schema='bronze')
    op.create_table('chain',
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('chain_base_name', sa.Text(), nullable=False),
    sa.Column('outlet_count', sa.Integer(), nullable=False),
    sa.Column('name_variants', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', name=op.f('pk_chain')),
    sa.UniqueConstraint('chain_base_name', name='uq_chain_chain_base_name'),
    schema='core'
    )
    op.create_table('grid_candidate',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('source_natural_id', sa.Text(), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=True),
    sa.Column('name_normalised', sa.Text(), nullable=True),
    sa.Column('chain_base_name', sa.Text(), nullable=True),
    sa.Column('branch_qualifier', sa.Text(), nullable=True),
    sa.Column('address_unit', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_locality', sa.Text(), nullable=True),
    sa.Column('city_canonical', sa.Text(), nullable=True),
    sa.Column('postcode_clean', sa.String(length=5), nullable=True),
    sa.Column('postcode_valid', sa.Boolean(), nullable=False),
    sa.Column('state_code', sa.Text(), nullable=True),
    sa.Column('latitude_clean', sa.Float(), nullable=True),
    sa.Column('longitude_clean', sa.Float(), nullable=True),
    sa.Column('coord_quality', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("coord_quality IN ('VALID','MISSING','NULL_ISLAND','OUT_OF_BOUNDS','REPAIRED_DECIMAL','REPAIRED_SPLIT')", name=op.f('ck_grid_candidate_coord_quality_enum')),
    sa.PrimaryKeyConstraint('candidate_id', name=op.f('pk_grid_candidate')),
    sa.UniqueConstraint('source_key', 'source_natural_id', name='uq_grid_candidate_source'),
    schema='core'
    )
    op.create_index('ix_candidate_blocking', 'grid_candidate', ['name_normalised', 'postcode_clean'], unique=False, schema='core')
    op.create_table('provider_code_supersession',
    sa.Column('superseded_code', sa.Text(), nullable=False),
    sa.Column('superseding_code', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('pattern_id', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_provider_code_supersession_confidence_range')),
    sa.CheckConstraint('superseded_code <> superseding_code', name=op.f('ck_provider_code_supersession_no_self_edge')),
    sa.PrimaryKeyConstraint('superseded_code', 'superseding_code', name=op.f('pk_provider_code_supersession')),
    sa.UniqueConstraint('superseded_code', 'superseding_code', name='uq_supersession_pair'),
    schema='core'
    )
    op.create_table('provider_outlet',
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('row_guid', sa.Text(), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=True),
    sa.Column('name_normalised', sa.Text(), nullable=True),
    sa.Column('chain_base_name', sa.Text(), nullable=True),
    sa.Column('branch_qualifier', sa.Text(), nullable=True),
    sa.Column('address_unit', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_locality', sa.Text(), nullable=True),
    sa.Column('city_canonical', sa.Text(), nullable=True),
    sa.Column('postcode_clean', sa.String(length=5), nullable=True),
    sa.Column('postcode_valid', sa.Boolean(), nullable=False),
    sa.Column('state_code', sa.Text(), nullable=False),
    sa.Column('postcode_state_mismatch', sa.Boolean(), nullable=True),
    sa.Column('latitude_clean', sa.Float(), nullable=True),
    sa.Column('longitude_clean', sa.Float(), nullable=True),
    sa.Column('coord_quality', sa.Text(), nullable=False),
    sa.Column('provider_type_code', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Text(), nullable=False),
    sa.Column('pmcare_panel_status', sa.Boolean(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('suspension_date', sa.DateTime(), nullable=True),
    sa.Column('operating_hours_present', sa.Boolean(), nullable=False),
    sa.Column('sourced_from_ingest_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("coord_quality IN ('VALID','MISSING','NULL_ISLAND','OUT_OF_BOUNDS','REPAIRED_DECIMAL','REPAIRED_SPLIT')", name=op.f('ck_provider_outlet_coord_quality_enum')),
    sa.PrimaryKeyConstraint('provider_code', name=op.f('pk_provider_outlet')),
    sa.UniqueConstraint('row_guid', name='uq_core_provider_outlet_row_guid'),
    schema='core',
    comment='Incumbent network from PR001. Never written by discovery.'
    )
    op.create_index('ix_core_outlet_blocking', 'provider_outlet', ['name_normalised', 'postcode_clean'], unique=False, schema='core')
    op.create_index('ix_core_outlet_chain', 'provider_outlet', ['chain_base_name'], unique=False, schema='core')
    op.create_table('remarks_signal',
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('raw_fragment', sa.Text(), nullable=False),
    sa.Column('pattern_id', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_remarks_signal_confidence_range')),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_remarks_signal')),
    schema='core'
    )
    op.create_index('ix_remarks_signal_type', 'remarks_signal', ['signal_type'], unique=False, schema='core')
    op.create_table('load_log',
    sa.Column('load_id', sa.String(length=36), nullable=False),
    sa.Column('ingest_id', sa.String(length=36), nullable=True),
    sa.Column('layer', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('rows_in', sa.BigInteger(), nullable=False),
    sa.Column('rows_out', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('load_id', name=op.f('pk_load_log')),
    schema='ops'
    )
    op.create_table('provider_contact',
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('doctor_name', sa.Text(), nullable=True),
    sa.Column('doctor_name_hash', sa.String(length=64), nullable=True),
    sa.Column('general_phone_no', sa.Text(), nullable=True),
    sa.Column('apps_phone_no', sa.Text(), nullable=True),
    sa.Column('einv_email', sa.Text(), nullable=True),
    sa.Column('einv_tin_no', sa.Text(), nullable=True),
    sa.Column('einv_sst_no', sa.Text(), nullable=True),
    sa.Column('hbrn', sa.Text(), nullable=True),
    sa.Column('gst_company_reg_no', sa.Text(), nullable=True),
    sa.Column('lawful_basis', sa.Text(), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=False),
    sa.Column('purpose_note', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('provider_code', name=op.f('pk_provider_contact')),
    schema='pii',
    comment='PERSONAL DATA — never in a shareable view or fixture.'
    )
    op.create_table('ref_category',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_category_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_category')),
    schema='staging',
    comment="ref_category: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_city',
    sa.Column('city_raw', sa.Text(), nullable=False),
    sa.Column('postcode_prefix', sa.String(length=2), nullable=False),
    sa.Column('city_canonical', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_city_source_enum')),
    sa.PrimaryKeyConstraint('city_raw', 'postcode_prefix', name=op.f('pk_ref_city')),
    schema='staging'
    )
    op.create_table('ref_lk180',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_lk180_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_lk180')),
    schema='staging',
    comment="ref_lk180: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_ownership',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_ownership_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_ownership')),
    schema='staging',
    comment="ref_ownership: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_payment_method',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_payment_method_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_payment_method')),
    schema='staging',
    comment="ref_payment_method: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_postcode_prefix_state',
    sa.Column('postcode_prefix', sa.String(length=2), nullable=False),
    sa.Column('modal_state_code', sa.Text(), nullable=False),
    sa.Column('modal_share', sa.Float(), nullable=False),
    sa.Column('observation_count', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_postcode_prefix_state_source_enum')),
    sa.PrimaryKeyConstraint('postcode_prefix', name=op.f('pk_ref_postcode_prefix_state')),
    schema='staging'
    )
    op.create_table('ref_provider_type',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_provider_type_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_provider_type')),
    schema='staging',
    comment="ref_provider_type: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_state',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_state_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_state')),
    schema='staging',
    comment="ref_state: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_status',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('confirmed_by_pnm', 'inferred', 'unknown')", name=op.f('ck_ref_status_source_enum')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ref_status')),
    schema='staging',
    comment="ref_status: Seeded only from what the data evidences. `meaning` stays NULL and `source` stays 'unknown' where we do not know — a documented NULL beats a plausible guess."
    )
    op.create_table('ref_user',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('raw_variants', sa.Text(), nullable=False),
    sa.Column('seen_in_columns', sa.Text(), nullable=False),
    sa.Column('first_seen_ingest_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_ref_user')),
    schema='staging'
    )
    op.create_table('outlet_candidate_link',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.Text(), nullable=False),
    sa.Column('blocking_key', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("decision IN ('auto_match','auto_new','review_queue','human_confirmed_match','human_confirmed_new')", name=op.f('ck_outlet_candidate_link_decision_enum')),
    sa.CheckConstraint('match_score >= 0.0 AND match_score <= 1.0', name=op.f('ck_outlet_candidate_link_match_score_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['core.grid_candidate.candidate_id'], name=op.f('fk_outlet_candidate_link_candidate_id_grid_candidate')),
    sa.ForeignKeyConstraint(['provider_code'], ['core.provider_outlet.provider_code'], name=op.f('fk_outlet_candidate_link_provider_code_provider_outlet')),
    sa.PrimaryKeyConstraint('link_id', name=op.f('pk_outlet_candidate_link')),
    sa.UniqueConstraint('candidate_id', 'provider_code', name='uq_link_candidate_provider'),
    schema='core'
    )
    op.create_index('ix_link_decision', 'outlet_candidate_link', ['decision'], unique=False, schema='core')
    op.create_table('outlet_chain_member',
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_outlet_chain_member_confidence_range')),
    sa.ForeignKeyConstraint(['chain_id'], ['core.chain.chain_id'], name=op.f('fk_outlet_chain_member_chain_id_chain')),
    sa.ForeignKeyConstraint(['provider_code'], ['core.provider_outlet.provider_code'], name=op.f('fk_outlet_chain_member_provider_code_provider_outlet')),
    sa.PrimaryKeyConstraint('provider_code', 'chain_id', name=op.f('pk_outlet_chain_member')),
    schema='core'
    )
    op.create_table('transform_log',
    sa.Column('transform_log_id', sa.String(length=36), nullable=False),
    sa.Column('load_id', sa.String(length=36), nullable=False),
    sa.Column('transform_name', sa.Text(), nullable=False),
    sa.Column('rows_considered', sa.BigInteger(), nullable=False),
    sa.Column('rows_changed', sa.BigInteger(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['ops.load_log.load_id'], name='fk_transform_load'),
    sa.PrimaryKeyConstraint('transform_log_id', name=op.f('pk_transform_log')),
    schema='ops'
    )
    op.create_index('ix_transform_log_load', 'transform_log', ['load_id'], unique=False, schema='ops')
    op.create_table('provider_outlet',
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('row_guid', sa.Text(), nullable=False),
    sa.Column('ingest_id', sa.String(length=36), nullable=False),
    sa.Column('row_ordinal', sa.BigInteger(), nullable=False),
    sa.Column('mix_row_id', sa.BigInteger(), nullable=True, comment='NOT A KEY. 15 rows collide in the source range 16,170-16,192. Deliberately unindexed and unconstrained; never use in a join.'),
    sa.Column('provider_type_code', sa.Text(), nullable=False),
    sa.Column('category_code', sa.Text(), nullable=False),
    sa.Column('payment_method_code', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Text(), nullable=False),
    sa.Column('state_code', sa.Text(), nullable=False),
    sa.Column('ownership_code', sa.Text(), nullable=True),
    sa.Column('lk180_code', sa.Text(), nullable=True),
    sa.Column('name_raw', sa.Text(), nullable=True),
    sa.Column('name_normalised', sa.Text(), nullable=True),
    sa.Column('chain_base_name', sa.Text(), nullable=True),
    sa.Column('branch_qualifier', sa.Text(), nullable=True),
    sa.Column('branch_qualifier_expanded', sa.Text(), nullable=True),
    sa.Column('address1_raw', sa.Text(), nullable=True),
    sa.Column('address2_raw', sa.Text(), nullable=True),
    sa.Column('address3_raw', sa.Text(), nullable=True),
    sa.Column('address_unit', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_locality', sa.Text(), nullable=True),
    sa.Column('city_raw', sa.Text(), nullable=True),
    sa.Column('city_canonical', sa.Text(), nullable=True),
    sa.Column('city_unmatched', sa.Boolean(), nullable=False),
    sa.Column('postcode_raw', sa.Text(), nullable=True),
    sa.Column('postcode_clean', sa.String(length=5), nullable=True),
    sa.Column('postcode_valid', sa.Boolean(), nullable=False),
    sa.Column('postcode_state_mismatch', sa.Boolean(), nullable=True, comment="True where the postcode's modal state disagrees with state_code. The postcode is treated as the more reliable of the two, but NEITHER field is overwritten. NULL where the prefix has no empirical mapping."),
    sa.Column('latitude_raw', sa.Float(), nullable=True),
    sa.Column('longitude_raw', sa.Float(), nullable=True),
    sa.Column('latitude_clean', sa.Float(), nullable=True),
    sa.Column('longitude_clean', sa.Float(), nullable=True),
    sa.Column('coord_quality', sa.Text(), nullable=False),
    sa.Column('coord_repair_note', sa.Text(), nullable=True),
    sa.Column('pmcare_panel_status', sa.Boolean(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('suspension_date', sa.DateTime(), nullable=True),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('sys_time_stamp', sa.DateTime(), nullable=True),
    sa.Column('acc_vendor_flag_date', sa.DateTime(), nullable=True, comment="Source sentinel 1900-01-01 ('not set') remapped to NULL; count logged."),
    sa.Column('standard_hour_from', sa.Time(), nullable=True),
    sa.Column('standard_hour_to', sa.Time(), nullable=True),
    sa.Column('public_hour_from', sa.Time(), nullable=True),
    sa.Column('public_hour_to', sa.Time(), nullable=True),
    sa.Column('operating_hours_present', sa.Boolean(), nullable=False),
    sa.Column('status_by', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Text(), nullable=True),
    sa.Column('modify_by', sa.Text(), nullable=True),
    sa.Column('gl_eligibility_approve_by', sa.Text(), nullable=True),
    sa.Column('mediline_user', sa.Boolean(), nullable=True),
    sa.Column('open_24_hours', sa.Boolean(), nullable=True),
    sa.Column('open_public_holidays', sa.Boolean(), nullable=True),
    sa.Column('gl_eligibility_status', sa.Boolean(), nullable=True),
    sa.Column('acc_vendor_flag', sa.Boolean(), nullable=True),
    sa.Column('is_pmr_used', sa.Boolean(), nullable=True),
    sa.Column('is_ame', sa.Boolean(), nullable=True),
    sa.Column('is_ame_mpm', sa.Boolean(), nullable=True),
    sa.Column('is_ltm', sa.Boolean(), nullable=True),
    sa.Column('is_efarma', sa.Boolean(), nullable=True),
    sa.Column('is_perkeso', sa.Boolean(), nullable=True, comment='True for only 114 rows — under-maintained. Not a PERKESO ground truth.'),
    sa.Column('is_oh', sa.Boolean(), nullable=True),
    sa.Column('no_doctor_male', sa.Boolean(), nullable=True, comment='BOOLEAN in source despite the name. Never an integer.'),
    sa.Column('no_doctor_female', sa.Boolean(), nullable=True),
    sa.Column('general_fax_no', sa.Text(), nullable=True),
    sa.Column('gst_reg_no', sa.Text(), nullable=True),
    sa.Column('gst_company_name', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sys_admin_remarks', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.CheckConstraint("coord_quality IN ('VALID','MISSING','NULL_ISLAND','OUT_OF_BOUNDS','REPAIRED_DECIMAL','REPAIRED_SPLIT')", name=op.f('ck_provider_outlet_coord_quality_enum')),
    sa.ForeignKeyConstraint(['category_code'], ['staging.ref_category.code'], name=op.f('fk_provider_outlet_category_code_ref_category')),
    sa.ForeignKeyConstraint(['create_by'], ['staging.ref_user.user_id'], name=op.f('fk_provider_outlet_create_by_ref_user')),
    sa.ForeignKeyConstraint(['gl_eligibility_approve_by'], ['staging.ref_user.user_id'], name=op.f('fk_provider_outlet_gl_eligibility_approve_by_ref_user')),
    sa.ForeignKeyConstraint(['lk180_code'], ['staging.ref_lk180.code'], name=op.f('fk_provider_outlet_lk180_code_ref_lk180')),
    sa.ForeignKeyConstraint(['modify_by'], ['staging.ref_user.user_id'], name=op.f('fk_provider_outlet_modify_by_ref_user')),
    sa.ForeignKeyConstraint(['ownership_code'], ['staging.ref_ownership.code'], name=op.f('fk_provider_outlet_ownership_code_ref_ownership')),
    sa.ForeignKeyConstraint(['payment_method_code'], ['staging.ref_payment_method.code'], name=op.f('fk_provider_outlet_payment_method_code_ref_payment_method')),
    sa.ForeignKeyConstraint(['provider_type_code'], ['staging.ref_provider_type.code'], name=op.f('fk_provider_outlet_provider_type_code_ref_provider_type')),
    sa.ForeignKeyConstraint(['state_code'], ['staging.ref_state.code'], name=op.f('fk_provider_outlet_state_code_ref_state')),
    sa.ForeignKeyConstraint(['status_by'], ['staging.ref_user.user_id'], name=op.f('fk_provider_outlet_status_by_ref_user')),
    sa.ForeignKeyConstraint(['status_code'], ['staging.ref_status.code'], name=op.f('fk_provider_outlet_status_code_ref_status')),
    sa.PrimaryKeyConstraint('provider_code', name=op.f('pk_provider_outlet')),
    sa.UniqueConstraint('provider_code', name='uq_provider_outlet_provider_code'),
    sa.UniqueConstraint('row_guid', name='uq_provider_outlet_row_guid'),
    schema='staging'
    )
    op.create_index('ix_staging_outlet_blocking', 'provider_outlet', ['name_normalised', 'postcode_clean'], unique=False, schema='staging')
    op.create_index('ix_staging_outlet_type_status', 'provider_outlet', ['provider_type_code', 'status_code'], unique=False, schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staging_outlet_type_status', table_name='provider_outlet', schema='staging')
    op.drop_index('ix_staging_outlet_blocking', table_name='provider_outlet', schema='staging')
    op.drop_table('provider_outlet', schema='staging')
    op.drop_index('ix_transform_log_load', table_name='transform_log', schema='ops')
    op.drop_table('transform_log', schema='ops')
    op.drop_table('outlet_chain_member', schema='core')
    op.drop_index('ix_link_decision', table_name='outlet_candidate_link', schema='core')
    op.drop_table('outlet_candidate_link', schema='core')
    op.drop_table('ref_user', schema='staging')
    op.drop_table('ref_status', schema='staging')
    op.drop_table('ref_state', schema='staging')
    op.drop_table('ref_provider_type', schema='staging')
    op.drop_table('ref_postcode_prefix_state', schema='staging')
    op.drop_table('ref_payment_method', schema='staging')
    op.drop_table('ref_ownership', schema='staging')
    op.drop_table('ref_lk180', schema='staging')
    op.drop_table('ref_city', schema='staging')
    op.drop_table('ref_category', schema='staging')
    op.drop_table('provider_contact', schema='pii')
    op.drop_table('load_log', schema='ops')
    op.drop_index('ix_remarks_signal_type', table_name='remarks_signal', schema='core')
    op.drop_table('remarks_signal', schema='core')
    op.drop_index('ix_core_outlet_chain', table_name='provider_outlet', schema='core')
    op.drop_index('ix_core_outlet_blocking', table_name='provider_outlet', schema='core')
    op.drop_table('provider_outlet', schema='core')
    op.drop_table('provider_code_supersession', schema='core')
    op.drop_index('ix_candidate_blocking', table_name='grid_candidate', schema='core')
    op.drop_table('grid_candidate', schema='core')
    op.drop_table('chain', schema='core')
    op.drop_index('ix_bronze_pr001_sha256', table_name='pr001_provider_master', schema='bronze')
    op.drop_index('ix_bronze_pr001_provider_code', table_name='pr001_provider_master', schema='bronze')
    op.drop_table('pr001_provider_master', schema='bronze')
    op.drop_table('pr001_generation', schema='bronze')
    # ### end Alembic commands ###
